### ISSUE TITLE
Cake 5 support?

### ISSUE THREAD

**Issue by stevewaffles** [ADmad/cakephp-jwt-auth#100]
Hi, any plans to make this supported for cake 5?

**Comment by ADmad** [comment]
Nope, since this plugin is for the AuthComponent which was already deprecated in CakePHP 4 and dropped in CakePHP 5.

The official [Authentication](https://github.com/cakephp/authentication) plugin includes support for JWT, so users should switch to that.

**Comment by stevewaffles** [comment]
Oh, ok. Thanks!
