### ISSUE TITLE
Using alternate fields to authenticate instead of username/password?

### ISSUE THREAD

**Issue by samueljrains** [ADmad/cakephp-jwt-auth#12]
Thank you so much for implementing this, it is extremely helpful in my development.  I have a question, if I wanted to use 'email' rather than 'username' to check the db, how would I modify the app?  I'm using an already existing database that uses 'email' instead of 'username' for the users credentials?  Also, the database uses 'pin' instead of 'password', how could I modify the structure to accommodate for the changes in database structure?  Thanks again!

**Comment by ADmad** [comment]
The authenticate class provided by this plugin doesn't use username password combination for authentication. It decodes jwt token in request to either get the user record or get the user id which is used to get user from database.

**Comment by bravo-kernel** [comment]
Hey Mr. @samueljrains, are you crossposting to keep us both busy? I just answered the literally exact same question on the jwt tutorial blog. :-1:

**Comment by samueljrains** [comment]
My apologizes!  I had some issue with the commenting system on the tutorial site (as I have never used that system before), and I was under the impression that it didn't post (on the tutorial).  I saw that it posted only after I had submitted this.  Sorry about that
