### ISSUE TITLE
getallheaders return headers case-insensitive in _getToken()

### ISSUE THREAD

**Issue by johnsoons** [ADmad/cakephp-jwt-auth#13]
I found something that might be useful and could save you a few hours of debugging. 
The getallheaders() function returns the header fields case-insensitive, so the header "Authorization" may not be found in certain requests.

http://php.net/manual/en/function.getallheaders.php#52029

Sorry, my English is limited, I used Google Translate

**Comment by ADmad** [comment]
I am curious which webserver you are using and why isn't `$_SERVER['HTTP_AUTHORIZATION']` set for you.

**Comment by johnsoons** [comment]
My front-end is using a grunt task to run the server and a proxy task to access the cakephp. Probably this is the step that the proxy headers are being modified. Since the headers are case-insensitive, add array_change_key_case() to return getallheaders() solve this issue.

What do you think of this idea?

Traduzidor by: Google Translator.
