### ISSUE TITLE
$this->auth->allow() Not Working in Non-User Controller

### ISSUE THREAD

**Issue by napalm684** [ADmad/cakephp-jwt-auth#14]
I am following the "Bravo" tutorial and I have the api method to add a User on the controller working but the same style of logic does not allow other methods to be public for some reason?

Here is the controller code I am trying to make the add method public on:

```php
<?php

namespace App\Controller\Api;

use App\Controller\Api\AppController;
use Cake\Event\Event;

class UserInfoController extends AppController
{
    public function beforeFilter(Event $event)
    {
        parent::beforeFilter($event);
        $this->Auth->allow('add');
    }

    public function add()
    {
        $this->Crud->on('afterSave', function(\Cake\Event\Event $event) {
            if ($event->subject->created) {
                $this->set('data', [
                    'id' => $event->subject->entity->id,
                    'message' => 'Request Saved!'
                ]);
                $this->Crud->action()->config('serialize.data', 'data');
            }
        });
        return $this->Crud->execute();
    }
}
```
I make the request http://localhost:8765/api/userinfo with POST and the correct JSON only to get a 401 unauthorized exception.  My UserController is practially identical to the "Bravo" tutorial and has no problems with the public add() method.  Is there something I am doing wrong or are the restrictions set by the plugin too "aggresive" for what I want to accomplish?

*UPDATE* - For some reason it will only work if I add the following route definition to alias the add method (but again only the alias will work not the direct api/userinfo call): 

```php
Router::connect('/api/userinfo/create', ['controller' => 'UserInfo', 'action' => 'add', 'prefix' => 'api']);
```

**Comment by ADmad** [comment]
There is nothing specific in the autheticate class provided by this plugin which you affect how Auth->allow() works. Your issue is either related to routing or Crud or AuthComponent config.

**Comment by WaseemAR** [comment]
Hi, i followed "Bravo" tutorial but i get Error: Call to a member function set() on Boolean while adding a new user. I have changed my database with columns (id,email, password, created, modified). What i am missing? is it that there should be "active" column in my db? Event after adding "active" column i get the same error.
Please help me as its been a head ace i am not getting it solved.

Thanks
