### ISSUE TITLE
Using on server can't be authorized

### ISSUE THREAD

**Issue by bobmulder** [ADmad/cakephp-jwt-auth#15]
I used this plugin for my project. However, the plugin gives me a token (which is valid), but can't validate it on a requests, which gives me a 'not Authorized' error.

Here I got some info:

## *Token request giving me the token*
![image](https://cloud.githubusercontent.com/assets/5465074/9959338/6e7b2994-5e13-11e5-97f7-b32b1bc3e8da.png)

## *A request which uses authorization*
![image](https://cloud.githubusercontent.com/assets/5465074/9959347/906c54ba-5e13-11e5-9554-d1427c013823.png)

## *Stack*
![image](https://cloud.githubusercontent.com/assets/5465074/9959366/b90808ec-5e13-11e5-949b-08ce65dd45d3.png)

**Comment by bravo-kernel** [comment]
Could you post the second screenshot with the Postman headers?

**Comment by bobmulder** [comment]
![image](https://cloud.githubusercontent.com/assets/5465074/9960444/e994a752-5e1a-11e5-81cc-bc9aa5199a03.png)

**Comment by bravo-kernel** [comment]
That Authorization header looks identical to mine (good).

**Comment by bravo-kernel** [comment]
Just for completion sake, figuring this out I came across the same caused by:

- incorrect setup of the component, solved by moving Auth configuration to initialize() function
- token expired while I was testing

**Comment by bobmulder** [comment]
Thanks for reply. However:
- all configuration is done in the initialize
- there were max 10 seconds between testing...

So still no solution. :S

**Comment by bravo-kernel** [comment]
Well, nothing left then but pasting the controller then if you ask me. There's not much else that can be reverse engineered from these screenshots (except the fact that I use a json/application Accept Header).

Or... wait for someone else to jump in

**Comment by ADmad** [comment]
> the plugin gives me a token (which is valid)

This plugin doesn't *give* any token. It provides an authentication class which only checks token provided in request.

Use http://jwt.io/ to decode your token and ensure it contains expected data.

**Comment by bobmulder** [comment]
@bravo-kernel I would like to refer to this plugin I am working on: https://github.com/cakemanager/cakephp-api. It uses the JWT-Auth plugin (note the plugin is incomplete).

The following section contains the actions:
https://github.com/cakemanager/cakephp-api/blob/master/src/Controller/Api/UsersController.php#L25-L55

This section adds the JWT Auth to the AuthComponent: https://github.com/cakemanager/cakephp-api/blob/master/src/Controller/Component/ApiBuilderComponent.php#L90

**Comment by bobmulder** [comment]
I am starting to think it's not in the `jwt-auth` plugin, neither in the `cakephp-api` [plugin](https://github.com/cakemanager/cakephp-api), but it's my own project. I took an older project of mine, and updated all dependencies. After some bugfixes I got it to work... So... I'll keep you up to date guys ;)

**Comment by bravo-kernel** [comment]
:+1: for adding your solution here Mr. @bobmulder

**Comment by bobmulder** [comment]
:+1: Thank you for your support Mr. @bravo-kernel! By the way, also thank you for your clear blog about api stuff and cake ;) Let's keep up the good work!
