### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by josegonzalez** [ADmad/cakephp-jwt-auth#17]
pls

**Comment by ADmad** [comment]
I plan do so soonish before I merge the `develop` into `master`. (It's pretty much ready if you wanna try)

**Comment by ADmad** [comment]
done

**Comment by josegonzalez** [comment]
FOC?

**Comment by ADmad** [comment]
It's fine here. I don't want to bother renaming and moving stuff :)

**Comment by josegonzalez** [comment]
lolfine
