### ISSUE TITLE
Problem with using Environment to provide Auth since plugin upgrade

### ISSUE THREAD

**Issue by voycey** [ADmad/cakephp-jwt-auth#18]
I haven't been able to catch you on IRC so I thought I would raise an issue, I'm not entirely sure where the problem is but since upgrading to the latest version of this plugin, setting an environment variable for authorisation for tests doesn't seem to be working:

I created this function to test it in one place and am running it through xdebug to inspect the data:

So at this point the plugin has returned the token and I have written it to the environment:

![http auth header problem](https://cloud.githubusercontent.com/assets/1065098/11261386/2f5b7436-8ec8-11e5-8a20-bc546d60b696.png)

Before I step into PHPUnit's GET function - you can see that I am Authorised in $_SESSION['Auth']

![auth ok before get](https://cloud.githubusercontent.com/assets/1065098/11261552/be6cfbda-8ec9-11e5-8b41-5d80ad1cd1d2.png)

I step into PHPUnit's GET function and can see the Environment variable is still set there so all seems good so far (I am also still Authorized in SESSION['Auth'])

![http auth header problem - step into get](https://cloud.githubusercontent.com/assets/1065098/11261415/6e2d5260-8ec8-11e5-9bc5-1ab96df1cca8.png)

But on the other side of it - Auth is now telling me I am not authorized and I really dont understand why? (The environment variable is still there at this point as well).

The line it occurs on is 109 of Dispatcher.php: ``` $result = $controller->startupProcess();```

Before this line my user is in Auth and as soon as the startupProcess is called on the comments controller it removes the Auth and replaces it with a redirect and a Flash message saying not Authorised

![http auth header problem - after get - auth not authorized](https://cloud.githubusercontent.com/assets/1065098/11261439/a200ac5e-8ec8-11e5-8eb7-f86df899e0c9.png)

My AppController initialize is:

```php
public function initialize()
    {
        parent::initialize();
        $this->loadComponent('Flash');
        $this->loadComponent('RequestHandler');
        $this->loadComponent('Crud.Crud', [
            'actions' => [
                'Crud.Index',
                'Crud.View'
            ]
        ]);
        $this->Crud->addListener('relatedModels', 'Crud.RelatedModels');
        $this->Crud->addListener('Crud.Api');
        $this->Crud->addListener('Crud.ApiQueryLog');

        //JWT Auth
        $this->loadComponent('Auth', [
            'loginAction' => [
                'controller' => 'Users',
                'action' => 'login',
            ],
            'unauthorizedRedirect' => false,
            'authenticate' => [
                'ADmad/JwtAuth.Jwt' => [
                    'storage' => (Configure::read('debug') ? "Session" : "Memory"),
                    'parameter' => 'token',
                    'queryDatasource' => true,
                    'userModel' => 'Users',
                    'scope' => ['Users.active' => 1],
                    'fields' => [
                        'id' => 'id'
                    ]
                ],
                'Form' => [
                    'passwordHasher' => [
                        'className' => 'Legacy'
                    ]
                ]
            ]
        ]);
    }
```

Am I doing something idiotic or is there some gotcha I need to be aware of in the new version? I saw your notes on ensuring the server set either $_SERVER or $_ENV - I have tried both to no avail.

I'll also add that for development purposes I am using Auth->setUser as well so I can run requests on the front end without having to use postman for all get requests

**Comment by voycey** [comment]
I updated composer and it flashed up some errors like this:
https://gist.github.com/voycey/ad793a1744e1f9b181cf 

So I rechecked the github repo and saw  ````composer require admad/cakephp-jwt-auth:2.0.x-dev````

So is this some magic mystery branch I have found that shouldn't have? 

I flicked back to 1.0 and everything is working fine - just a bit confused!

**Comment by ADmad** [comment]
Earlier the master branch was aliased as `1.0.x-dev`. Now `1.0.0` release has been done and master is instead aliased as `2.0.x-dev`. So you can update your composer file to use version `~1.0` or `2.0.x-dev` if you want to use the new version. 2.x has backwards incompatible table so check the README.

**Comment by voycey** [comment]
I think this issue was caused on the 2.x branch (works fine on ~1.0) - so the issue still stands, I would like to upgrade eventually to the new version - so any idea what was causing the authentication issue described above? I did follow the readme and made the changes mentioned in there - it seems like the plugin works fine - it just seems to be during dispatch that it wipes out the Auth?

**Comment by ADmad** [comment]
- 2.x requires `fields.username` your screenshot shows `fields.id`. You should also use `'checkAuthIn' => 'Controller.initialize'
- Mixing stateless (JwtAuth) and stateful (Form) authenticator is a bad idea. It's very likely to cause you problems in production.
- Using `Session` instead of

**Comment by voycey** [comment]
Ill give these a go tomorrow - Thanks! 
The majority of the last things on there are for testing only and wont be in production - think I'm probably at a point where i can take them out.

Appreciate the help :)

**Comment by voycey** [comment]
I have it working now with a few changes as above - 
One question though, you say: 

Mixing stateless (JwtAuth) and stateful (Form) authenticator is a bad idea. It's very likely to cause you problems in production.

This was how Bravo_Kernel showed it in his example, I also need to have a legacy password hasher as I am creating this new system to talk to our previous database which has a custom rolled Auth that cant easily be ported to bcrypt (but is secure enough for our needs). 
What kind of problems can you foresee? I thought that Form Auth was needed to check the user from the request data to see if a token should be generated first off (e.g. the users first login?)

Thanks again :)

**Comment by GabrielAraujo** [comment]
I'm having this issue.. On localhost it works normally but on amazon ebs it is refusing connections..

`$this->loadComponent('RequestHandler');
        $this->loadComponent('Crud.Crud', [
            'actions' => [
                'Crud.Index',
                'Crud.View',
                'Crud.Add',
                'Crud.Edit',
                'Crud.Delete'
            ],
            'listeners' => [
                'Crud.Api',
                'Crud.ApiPagination',
                'Crud.ApiQueryLog'
            ]
        ]);
        $this->loadComponent('Auth', [
            'storage' => 'Memory',
            'authenticate' => [
                'ADmad/JwtAuth.Jwt' => [
                    'parameter' => 'token',
                    'userModel' => 'Users',
                    'scope' => ['Users.active' => 1],
                    'fields' => [
                        'username' => 'id'
                    ],
                    'queryDatasource' => true
                ]
            ],
            'unauthorizedRedirect' => false,
            'checkAuthIn' => 'Controller.initialize'
        ]);`
