### ISSUE TITLE
RESTfull API example

### ISSUE THREAD

**Issue by nicolabortignon** [ADmad/cakephp-jwt-auth#2]
Hi,
great job! 

It would be nice to have a full example of how to implement RESTful api for integrating JWT auth with client side apps

**Comment by ADmad** [comment]
I am not very good at writing docs. I wish someone could help out with an end to end usage example :)

**Comment by ADmad** [comment]
The readme now has a link to blog post by Bravo Kernel with end to end usage example.

**Comment by rvoliquino** [comment]
Hi ADMad,

I just want to say thank you for all the documentaton that you have
provided in us.  This will be a great help in our on-going project
development.


Kind Regards,

Ruben

**Comment by bravo-kernel** [comment]
Blog found here: http://www.bravo-kernel.com/2015/04/how-to-add-jwt-authentication-to-a-cakephp-3-rest-api/
