### ISSUE TITLE
'storage' => 'Memory' must stay outside 'authenticate' node

### ISSUE THREAD

**Issue by danielfpedro** [ADmad/cakephp-jwt-auth#20]
I was using like the readme example but was not behaving stateless:

    $this->loadComponent('Auth', [
            'authenticate', [
                'ADmad/JwtAuth.Jwt' => [
                    'storage' => 'Memory'
                    'userModel' => 'Users',
                    'fields' => [
                        'username' => 'id'
                    ],

                    'parameter' => 'token',

                    // Boolean indicating whether the "sub" claim of JWT payload
                    // should be used to query the Users model and get user info.
                    // If set to `false` JWT's payload is directly returned.
                    'queryDatasource' => true,
                ]
            ],
            'unauthorizedRedirect' => false,
            'checkAuthIn' => 'Controller.initialize',
        ]);

So I made a request sending the `JWT` and all requests after that even if without `JWT` was `authorized` and if I did `$this->Auth->user()` I was getting the user, again, even if when I was not sending the `JWT`.

I just moved the `storage` outside `authenticate` node and now everything is working properly:

      $this->loadComponent('Auth', [
            'storage' => 'Memory'
            'authenticate', [
                'ADmad/JwtAuth.Jwt' => [
                    'userModel' => 'Users',
                    'fields' => [
                        'username' => 'id'
                    ],

                    'parameter' => 'token',

                    // Boolean indicating whether the "sub" claim of JWT payload
                    // should be used to query the Users model and get user info.
                    // If set to `false` JWT's payload is directly returned.
                    'queryDatasource' => true,
                ]
            ],
            'unauthorizedRedirect' => false,
            'checkAuthIn' => 'Controller.initialize',
        ]);

**Comment by ADmad** [comment]
Woops..
