### ISSUE TITLE
Usermodel

### ISSUE THREAD

**Issue by Piclebeuh** [ADmad/cakephp-jwt-auth#23]
I've followed this tuto : http://www.bravo-kernel.com/2015/04/how-to-add-jwt-authentication-to-a-cakephp-3-rest-api/ 

I tried to change the entity "Users" by "Logins". "Users" uses username and password for authentication, and "Logins" uses email and password as fields for authentication.
It's working with Users but not with Logins.
I can't find where's the issue. You can check the work I've done for this issue on this repo : https://github.com/Piclebeuh/cake3api.app

Thanks

**Comment by ADmad** [comment]
Since your `Login` model uses `email` and `password` specify `'username' => 'emai'` in your [Form](https://github.com/Piclebeuh/cake3api.app/blob/master/src/Controller/Api/AppController.php#L34) authenticate config.

**Comment by ADmad** [comment]
For `JwtAuth` also use `'fields' => [ 'username' => 'id']` as shown in README.  That tutorial is v1 of this plugin.

**Comment by bravo-kernel** [comment]
I will update the tutorial this weekend, until then take a look at this already updated code https://github.com/bravo-kernel/application-examples/pull/1/files

**Comment by Piclebeuh** [comment]
Thanks ! :)

**Comment by bravo-kernel** [comment]
Tutorial is updated as well :relaxed:
