### ISSUE TITLE
Extend _findUser

### ISSUE THREAD

**Issue by olivero86** [ADmad/cakephp-jwt-auth#24]
I have a login-form where the user can either enter e-mail, nickname or mobile no as username. At the moment it obviously works only with one field. What is the best way to extend that functionality? I tried to extend the class JwtAuthenticate and override _findUser but it didn't work so far.

**Comment by ADmad** [comment]
JwtAuthenticate has nothing to do with form based login.

**Comment by bravo-kernel** [comment]
In case @olivero86 is using form to post credentials for e.g. refreshing/requesting the JWT token (as described in the tutorial): check https://github.com/FriendsOfCake/Authenticate, it does what you need.
