### ISSUE TITLE
Question: would it be difficult to backport to CakePHP 2.x

### ISSUE THREAD

**Issue by sebastienbarre** [ADmad/cakephp-jwt-auth#33]
Just curious. Would it be difficult to backport this plugin to CakePHP 2.x? Or is it an effort not worth undertaking?
Thank you

**Comment by ADmad** [comment]
It shouldn't be too difficult, but I am not interested in maintaining a Cake 2.x compatible version :)

For 2.x you can checkout https://github.com/burzum/cakephp-bz-utils/blob/master/Controller/Component/Auth/JwtTokenAuthenticate.php

**Comment by sebastienbarre** [comment]
No worries, this was for me to contribute -- just wanted an informed opinion. Thanks!
