### ISSUE TITLE
TOKEN EXPIRED : 401 response code instead of 500

### ISSUE THREAD

**Issue by ayman-alkom** [ADmad/cakephp-jwt-auth#36]
I wonder if it is more likely for plugin to make the response code **401** when the **token expired** error rises.
the current response code is **500** 
I already know it can be done in my project ;)

**Comment by ADmad** [comment]
Are you checking with debug on or off?  With debug off you should get a 401 response code.

**Comment by ayman-alkom** [comment]
the debug is on

**Comment by ADmad** [comment]
With debug on the 500 is expected since I am directly throwing the exception generated by `Jwt::decode()` for easy debugging. With debug off you will get a 401.

**Comment by ayman-alkom** [comment]
Up to me 500 was not expected, and the message passed to the 401 was enough.
we may pass some more information about the original exception to the auth exception for debug issues

**Comment by ayman-alkom** [comment]
I now understand the reason that made you directly throwing the exception generated by Jwt::decode() when debug is on.
it is  needed when you build this plugin and test it but not when someone using it in his project.

**Comment by ADmad** [comment]
No it was not for plugin development, it's to make debugging easier for the app developer as `Jwt::decode()` can throw multiple types of exceptions. This behavior is similar to how for e.g. you would get a MissingController exception with debug on but that would be turned in into a NotFoundException with debug off.

I am not keen on changing this behavior. As I stated earlier with debug off you will always get a 401 if authentication fails.

**Comment by ayman-alkom** [comment]
Ok
Then I will do it in my project :)
