### ISSUE TITLE
Issues with production server

### ISSUE THREAD

**Issue by bstras21** [ADmad/cakephp-jwt-auth#46]
Hello, I have been looking all around for a couple hours with no answer. I completed this tutorial:

http://www.bravo-kernel.com/2015/04/how-to-build-a-cakephp-3-rest-api-in-minutes/

It works great locally but the same code on my production server  (Siteground) and I keep getting this error:

{
  "message": "You are not authorized to access that location.",
  "url": "/customers",
  "code": 401
}

I did add this to .htaccess:

RewriteEngine On
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]

I also checked http://jwt.io/ and validated my token, not sure what to do, please point me in the right direction

here is my UsersController:

     <?php
     namespace App\Controller;

     use Cake\Event\Event;
     use Cake\Network\Exception\UnauthorizedException;
     use Cake\Utility\Security;
     use Firebase\JWT\JWT;

     class UsersController extends AppController{
         public function initialize(){
             parent::initialize();
             $this->Auth->allow(['add', 'token']);
        }
    
    public function add(){
        $this->Crud->on('afterSave', function(Event $event) {
            if ($event->subject->created) {
                $this->set('data', [
                    'id' => $event->subject->entity->id,
                    'token' => JWT::encode(
                        [
                            'sub' => $event->subject->entity->id,
                            'exp' =>  time() + 604800
                        ],
                    Security::salt())
                ]);
                $this->Crud->action()->config('serialize.data', 'data');
            }
        });
        return $this->Crud->execute();
    }
    
    
    
    
    public function token(){
        $user = $this->Auth->identify();
        if (!$user) {
            throw new UnauthorizedException('Invalid username or password');
        }

        $this->set([
            'success' => true,
            'data' => [
                'token' => JWT::encode([
                    'sub' => $user['id'],
                    'exp' =>  time() + 604800
                ],
                Security::salt())
            ],
            '_serialize' => ['success', 'data']
        ]);
    }
    

     }

**Comment by bravo-kernel** [comment]
I believe I pointed you to the [CakePHP Slack community](http://cakesf.herokuapp.com/) for support based on your comment on my blog. Did you go there for help?

**Comment by bstras21** [comment]
I will, I haven't received an answer from one of my last questions so was hesitant. I'll do it now.

**Comment by bstras21** [comment]
Well, no help on the Slack community?

**Comment by ADmad** [comment]
Given that the exact same code works fine locally there must be some environment issue. You'll have to step through the code and figure out the problem yourself.

**Comment by bstras21** [comment]
**Figured it out:**
I had to add this to the **webroot folder** .htaccess:
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization},L]

**Comment by bravo-kernel** [comment]
👍🏼 👏🏼 🎉
