### ISSUE TITLE
Manage multiple tokens

### ISSUE THREAD

**Issue by jigzat** [ADmad/cakephp-jwt-auth#50]
Thank you for this, I have a situation where I use a separate table for users and tokens joined by a one-to-many relationship, is there way to make it work without having to add an additional username field at the tokens table? Would it check all the available keys or just the first one it finds?

**Comment by ADmad** [comment]
What tokens are you taking about? This plugin doesn't need the jwt tokens to be saved in db.

**Comment by jigzat** [comment]
Oh sorry, I missed the `FormAuthenticate` part in a tutorial and I assumed this configuration parameters `'parameter' => 'token',
                    'userModel' => 'Users',
 `
were used to look up the token as a column value
