### ISSUE TITLE
Token check without expiration

### ISSUE THREAD

**Issue by Josecanalla** [ADmad/cakephp-jwt-auth#51]
Hello, is there a way to do not check the token expiration? So if the token is expired, I want to get logged in correctly.

**Comment by ADmad** [comment]
No, that would be against JWT specs.

**Comment by Josecanalla** [comment]
Ok, and which is the max value can I set in "$maxValue" var?
`JWT::encode(['sub' => $abonado->id, 'exp' =>  time() + $maxValue], Security::salt());`

**Comment by thiagoreri** [comment]
How do I control the expiration time of the login?
