### ISSUE TITLE
Authentication does not work when the user password is in clear text

### ISSUE THREAD

**Issue by ironbone** [ADmad/cakephp-jwt-auth#55]
I know we should ever encrypt passwords but I just do not understood why it does not work ;)

When I add to my User Entity
```
use Cake\Auth\DefaultPasswordHasher;

protected function _setPassword($password)
    {
        return (new DefaultPasswordHasher)->hash($password);
    }
```
every thing works well. But without those lines (I just not encrypt passwords) the authentication does not work. The token is ok.

**Comment by ADmad** [comment]
The jwt authenticator class has nothing to do with the password field. It only cares about the JWT token.

**Comment by ironbone** [comment]
I know it, therefore it is surprising for me. I can send you an example
