### ISSUE TITLE
how to use with Acl ?

### ISSUE THREAD

**Issue by leandrofreires** [ADmad/cakephp-jwt-auth#57]
How to use with acl

I set up all the acl and authentication but by doing a get it returns me
AclNode :: node () - Could not find Aros node identified by "Array ([Aros0.model] => Users [Aros0.foreign_key] => 1)"

My controller

`$this->loadComponent('Auth', [
            'authorize' => [
                'Acl.Actions' => ['actionPath' => 'controllers/']
            ],
            'authenticate' => [
                AuthComponent::ALL => ['userModel' => 'Employes'],
                'Form' => [
                    'fields' => [
                        'username' => 'email',
                        'password' => 'senha'
                    ],
                    'scope' => ['Employes.status' => 1]
                ],
                'ADmad/JwtAuth.Jwt' => [
                    'parameter' => 'token',
                    'scope' => ['Employes.status' => 1],
                    'queryDatasource' => true
                ]
            ],
            'unauthorizedRedirect' => false,
            'checkAuthIn' => 'Controller.initialize',
            'storage' => 'Memory'
        ]);`

The name of my tables  employes and roles where they are configured

Employes entity
`public function parentNode()
    {
        if (!$this->id) {
            return null;
        }
        if (isset($this->role_id)) {
            $roleId = $this->role_id;
        } else {
            $employes = TableRegistry::get('Employes');
            $employes = $employes->find('all', ['fields' => ['role_id']])->where(['id' => $this->id])->first();
            $roleId = $employes->role_id;
        }
        if (!$roleId) {
            return null;
        }
        return ['Roles' => ['id' => $roleId]];
    }`

**Comment by ADmad** [comment]
This plugin only provides authentication adapter, it has nothing to do with authorization (which is what ACL is for).
