### ISSUE TITLE
CakePHP 3.6 deprecation:  Deprecated (16384): The `scope` and `contain` options for Authentication are deprecated. Use the `finder` option instead to define additional conditions. - /home/public_html/vendor/admad/cakephp-jwt-auth/src/Auth/JwtAuthenticate.php, line: 105 [CORE/src/Core/functions.php, line 305]

### ISSUE THREAD

**Issue by Teonnyn** [ADmad/cakephp-jwt-auth#62]
Running into this problem with 3.6, though things seem to be otherwise working. This is occurring with 

    public function __construct(ComponentRegistry $registry, $config)
    {
        $this->setConfig([
            'header' => 'authorization',
            'prefix' => 'bearer',
            'parameter' => 'token',
            'queryDatasource' => true,
            'fields' => ['username' => 'id'],
            'unauthenticatedException' => UnauthorizedException::class,
            'key' => null,
        ]);

        if (empty($config['allowedAlgs'])) {
            $config['allowedAlgs'] = ['HS256'];
        }

        parent::__construct($registry, $config);
    }

Is there anything I can do to fix this in code?

**Comment by ADmad** [comment]
`JwtAuthenticate` class doesn't use `scope` or `contain` keys anywhere. They must be coming from your app config.
