### ISSUE TITLE
getToken() causes authentication error when using query param 'token'

### ISSUE THREAD

**Issue by luukau** [ADmad/cakephp-jwt-auth#66]
The function getToken() was recently changed and caused an authentication error in my project. I think an incorrect variable was introduced in a recent change when a token is provided as a query param.

Ie. $this->_token was possibly incorrectly replaced by $token

Made the change in my fork to check and test.

**Comment by ADmad** [comment]
Please provide an example use case to reproduce the error or open a pull request with failing test case and/or fix.

**Comment by ADmad** [comment]
Yeah sorry, not sure how I missed the failing tests earlier. My excuse is I have been trying to get all plugins I maintain play well with 3.6 as quickly as possible :D

**Comment by felipesudrj** [comment]
Do you have a solution to this problem?
