### ISSUE TITLE
401 Unauthorized access even on valid token

### ISSUE THREAD

**Issue by anuj9196** [ADmad/cakephp-jwt-auth#73]
I'm using `CakePHP 3.6` and this plugin to add REST to my application.

All works fine in localhost but after moving to the server, it gives **401 error**
```
{
    "success": false,
    "data": {
        "message": "You are not authorized to access that location.",
        "url": "/api/client_accounts",
        "code": 401
    }
}
```

I have posted a question with more detail on Stackoverflow.

[https://stackoverflow.com/q/52286806/3719167](https://stackoverflow.com/q/52286806/3719167)

I have also added the following in **.htaccess**

```
<IfModule mod_rewrite.c>
    RewriteEngine on
    RewriteRule    ^(\.well-known/.*)$ $1 [L]
    RewriteRule    ^$    webroot/    [L]
    RewriteRule    (.*) webroot/$1    [L]
    
    RewriteCond %{HTTP:Authorization} ^(.*)
    RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]
</IfModule>

```

**Comment by DerErich** [comment]
Had the same problem just now, after updating Cake 3.6.12 (now 3.6.14).
I added the given line to my .htaccess file in webroot and now it works as before. Thank you very much for your help!
