### ISSUE TITLE
Storage

### ISSUE THREAD

**Issue by bobmulder** [ADmad/cakephp-jwt-auth#8]
Hey,

Do you have any plans to store the tokens somewhere to work with refresh-tokens?
The plugin looks good and trying it :)

Some extra docs would be welcome (as said earlier). Maybe I got some time once....

Greetz

Bob

**Comment by ADmad** [comment]
> Do you have any plans to store the tokens somewhere to work with refresh-tokens?

None for the time being (PRs are welcome). I am not really familiar with refresh tokens nor had a use case for it personally.

> Some extra docs would be welcome

I don't think I can do any better than the wonderful blog post by Bravo Kernel (which I have already linked in the readme).
