### ISSUE TITLE
Cakephp 4 version

### ISSUE THREAD

**Issue by fred2ryck** [ADmad/cakephp-jwt-auth#86]
Hi, and many thanks for this plugin. Do you plan to upgrade it for cakephp 4 ?

**Comment by ADmad** [comment]
The new [authentication](https://github.com/cakephp/authentication) lib already has support for JWT, so I am not sure if upgrading this lib to support 4.x has much value.

But if there's public demand I don't mind updating.

**Comment by swiffer** [comment]
Mixed feelings - would simplyfy migrating to CakePHP 4.0 but If I understood correctly authComponent ist deprecated anyway...

**Comment by ADmad** [comment]
Yes the core `AuthComponent` and related classes are deprecated (but will not be removed until 5.0) and this plugin provides authenticate class for the component.

**Comment by fred2ryck** [comment]
Thx for the response. I will try to deal with the standard JWT implementation !

**Comment by Hamfri** [comment]
I wish this library could be updated to support cakePHP 4+. It would solve so many problems some of us are facing upgrading old applications to 4.x.x.

**Comment by ADmad** [comment]
I would be happy to make new Cake 4 compatible release if someone makes a pull request.
