### ISSUE TITLE
Refresh token

### ISSUE THREAD

**Issue by Maniraj-Webner** [ADmad/cakephp-jwt-auth#90]
Hi,

I have two issues that whenever a token is expired there is no documentation of refresh token. How can I add refresh token functionality?

2, I'm not able to customize the route without.json extension, at the end of the method.
I want **Http://localhost/api/{slug}**

**Comment by ADmad** [comment]
1. There is no refresh token functionality in the plugin, it's upto you to implement it.

2. The plugin doesn't do anything related to routing either. So again that's up to you to sort out.
