### ISSUE TITLE
Customise Url

### ISSUE THREAD

**Issue by Maniraj-Webner** [ADmad/cakephp-jwt-auth#91]
I have implemented ADmad JWT plugin. I’m facing problem to customise API url
I have this URL : http://localhost/api/users/token.json

wants to change above url to this url : http://localhost/api/token
I also tried http://localhost/api/users/token
It gives me an error that “the requested address
‘/api/users/token’ was not found on this server.”

How can I customise this?

**Comment by ADmad** [comment]
This plugin does not set any routes so your issue is unrelated to this plugin.

**Comment by Maniraj-Webner** [comment]
The below content is given in the tutorial

Verify Token Request
To verify your setup try requesting a token for the newly created user by posting JSON data to your API using:
URL http://cake3api.app/api/users/token

My requirement http://localhost/api/users/token
working URL http://localhost/api/users/token.json
