### ISSUE TITLE
Json format

### ISSUE THREAD

**Issue by Maniraj-Webner** [ADmad/cakephp-jwt-auth#92]
I have implemented your Admad JWT CakePHP tutorial.  I'm writing the API URL like this "http://localhost/api/fetch-al3-output" without "http://localhost/api/fetch-al3-output.json". It is working fine when token not expired but it throws an error when my token got expired. it gives me an error in HTML not in JSON format

  <div id="content">
                <h2>Expired token</h2>
                <p class="error">
                    <strong>Error: </strong>
    The requested address
                    <strong>'/api/fetch-al3-output'</strong> was not found on this server.
                </p>
            </div>

I'm converting my methods output with this code " $this->RequestHandler->renderAs($this, 'json');"  but I'm not able to covert the token expired message in json format.

![token_error](https://user-images.githubusercontent.com/54585663/87403345-60745300-c5da-11ea-8b2f-dae9c9647514.png)
![token_expired_json](https://user-images.githubusercontent.com/54585663/87403373-69fdbb00-c5da-11ea-96c6-39b97a2b6e34.png)

I want to show a token expired message in JSON without using ".json" extension in URL like second screenshot.

**Comment by ADmad** [comment]
You will have to customize either the `ErrorController` or `ExceptionRenderer` to return JSON response for the exception(s). Use one of CakePHP's help forums to get info on how to achieve that.

**Comment by Maniraj-Webner** [comment]
@ADmad 
Do you have any guide to customizing this ErrorController or ExceptionRenderer? I have raised a ticket on the CakePHP forum but not find any solution till now. A small help is highly appreciable.

**Comment by ishan-biztech** [comment]
Hi @Maniraj-Webner,

I've replied in the [forum](https://discourse.cakephp.org/t/customise-error-controller/8066/3?u=bizdev). Please have a look and let us there if you've any queries.

**Comment by Maniraj-Webner** [comment]
Thanks @ishan-biztech
