### ISSUE TITLE
Authorization Error

### ISSUE THREAD

**Issue by Maniraj-Webner** [ADmad/cakephp-jwt-auth#94]
I'm facing an error on passing authorization header, In one request I'm able to generate token but when I'm using this token in another call for any functionality. It gives me an error
" You are not authorized to access that location". 

I have also changed the  .htaccess file code in webroot by adding this code but it not work for me.
This is my .htaccess file code.

<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteBase /
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]

    RewriteCond %{HTTP:Authorization} ^(.*)
    RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]
    SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1

</IfModule>

**Comment by ADmad** [comment]
Please use one of CakePHP's help forums.
